export const actionTypes = {
  getProducts: 'GET_PRODUCTS',
  getProduct: 'GET_PRODUCT',
  createProduct: 'CREATE_PRODUCTS',
  deleteProduct: 'DELETE_PRODUCTS',
  editProduct: 'EDIT_PRODUCTS',
  createSize: 'CREATE_SIZE',
  createCategory: 'CREATE_CATEGORY',
  getCategories: 'GET_CATEGORIES',
  getSizes: 'GET_SIZE',
  createColor: 'CREATE_COLOR',
  getColors: 'GET_COLOR',
  login: 'LOGIN_REQUEST',
  getOrders: 'GET_ORDERS',
  getOrder: 'GET_ORDER',
  updateOrder: 'UPDATE_ORDER',
  createOrder: 'CREATE_ORDER',
  deleteOrderItem: 'DELETE_ORDER_ITEM',
  deleteAllOrderItems: 'DELETE__ALL_ORDER_ITEM',
};
